name: test-syntax

on: [push, pull_request]

jobs:
  run-syntax-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Scarpet
      - run: |
          rm Scarpet/examples/*test*.{svg,html,png}
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          package-name: Scarpet
          package-path: Scarpet
      - uses: SublimeText/UnitTesting/actions/run-syntax-tests@v1