name: run-tests

on: [push, pull_request]

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        st-version: [4]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: Scarpet
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: ${{ matrix.st-version }}
          package-name: Scarpet
          package-path: Scarpet
      - run: ls $SUBLIME_TEXT_PACKAGES
      - run: ls $SUBLIME_TEXT_PACKAGES/$PACKAGE
      - run: ls $SUBLIME_TEXT_PACKAGES/User
      - run: subl
      - uses: SublimeText/UnitTesting/actions/run-tests@v1

  syntax-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Scarpet
      - run: |
          rm -f Scarpet/examples/*test*.{svg,html,png}
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          package-name: Scarpet
          package-path: Scarpet
      - uses: SublimeText/UnitTesting/actions/run-syntax-tests@v1